//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Books
    {
        [Display(Name = "#")]
        public int id { get; set; }
        [Display(Name = "Nombre del libro")]
        public string bookName { get; set; }
        [Display(Name = "Autor del libro")]
		public string author { get; set; }
        [Display(Name = "Fecha de lanzamiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/DD/yyyy}")]
        [DataType(DataType.DateTime)]
		public System.DateTime date { get; set; }
	}
}
